Add /proc/sys/kernel/pid_max
deislabs/mystikos pull request #1013
Opened 2021-11-12 00:04 UTC by RRathna

This file is required for syscall sched_getparam, sched_getscheduler and sched_setscheduler to function correctly. And for their relevant ltp tests be enabled

Signed-off-by: Rathna Ramesh <rathna1993@gmail.com>

2022-01-07 20:25 UTC, paulcallen requested changes

2022-01-07 20:25 UTC, paulcallen commented on include/myst/thread.h
> +MYST_UNUSED static uint8_t bitmap_pid[4096] = {0};
this is wrong. This should be a global variable in something like thread.c itself, not defined in the header. This is adding this arrary to every source file that includes thread.h which is cauing a lot of bloat.
By all means make this an extern variable in the header, but only define it once.

2022-01-10 18:56 UTC, paulcallen approved these changes

2022-06-13 22:44 UTC, radhikaj commented
Closing this for now, please reopen if you would like to update

2022-06-13 22:44 UTC, closed without merging