protect filesystems from signals
deislabs/mystikos pull request #1297
Opened 2022-04-05 01:48 UTC by paulcallen

Signed-off-by: Paul Allen <paul.c.allen@microsoft.com>

2022-04-06 16:55 UTC, mikbras commented on kernel/lockfs.c
> +#else
ulong max is always 64-bit on x86_64.

2022-04-06 17:37 UTC, mikbras requested changes
I created a new branch (paulcallen/lockfs-signal-v2) with two minor modifications:
- included musl sigfillset.c in kernel directly to avoid licensing issue from cut-n-paste.
- factored out LOCK/UNLOCK macros by moving conditional check inside lock() function.

2022-04-06 17:37 UTC, mikbras commented
I can't see anything functionally wrong but needed to at least work around licensing implication of including musl code in the kernel.

2022-04-06 19:33 UTC, paulcallen commented
pulled in the sigfillset.c change from your branch

2022-04-06 20:23 UTC, paulcallen commented
unfortunately, moving the signal disabling into the lock creates a race condition that can leave the lock active when an exception occurs.

2022-04-07 21:42 UTC, mikbras approved these changes
Thank you for doing this. Looks good.

2022-04-07 21:43 UTC, merged