Fix issue 1467
deislabs/mystikos pull request #1493
Opened 2023-08-17 14:35 UTC by isil-oz

2023-08-17 14:44 UTC, isil-oz commented
@microsoft-github-policy-service agree

2023-09-11 16:30 UTC, vtikoo requested changes
Thanks for the PR @isil-oz, overall looks good! Please take a look at the comments.
Also please squash your commits into a single commit, and provide a meaningful commit message.

2023-09-11 16:30 UTC, vtikoo commented on kernel/mmanutils.c
> +    //printf("max_usage %ld current_usage %ld\n", _mman.max_usage, _mman.current_usage);
Remove commented line

2023-09-11 16:30 UTC, vtikoo commented on kernel/mmanutils.c
> +int set_mem_usage(long length)
Consider function names like `update_mem_usage` or `register_mem_usage`. This function is accounting for the memory usage update caused by the current allocation/deallocation.

2023-09-11 16:30 UTC, vtikoo commented on kernel/mmanutils.c
> +    int ret = 0;
This function always returns 0, consider changing return type to void.

2023-09-11 16:30 UTC, vtikoo commented on kernel/mmanutils.c
> +        //Update mem usage myst_mmap
As max usage is only displayed if `--perf` was passed on command line, its better to apply the same condition here.

2023-09-11 16:30 UTC, vtikoo commented on kernel/mmanutils.c
> +    set_mem_usage((long)new_size - (long)old_size);
Same as above, put behind `--perf` option check.

2023-09-11 16:30 UTC, vtikoo commented on kernel/mmanutils.c
> +    set_mem_usage(-1 * (long)length);
Same as above, put behind `--perf` option check.

2023-09-11 16:30 UTC, vtikoo commented on kernel/enter.c
> +        /* print out the maximum value it saw during an application's lifetime at shutdown */
```suggestion
        /* print out the maximum memory usage seen during an application's lifetime at shutdown */
```

2023-09-11 18:41 UTC, vtikoo commented
We don't have `--perf` documented in the usage strings, please document the existing functionality and the new additions you've made. 
The usage strings are here -
Linux target - https://github.com/deislabs/mystikos/blob/main/tools/myst/host/exec_linux.c#L126
SGX target - https://github.com/deislabs/mystikos/blob/main/tools/myst/host/exec.c#L461

For existing `--perf` functionality you can add - reports time taken to boot and on shutdown reports time spent on each syscall.

2023-09-22 10:40 UTC, isil-oz commented
> We don't have `--perf` documented in the usage strings, please document the existing functionality and the new additions you've made. The usage strings are here - Linux target - https://github.com/deislabs/mystikos/blob/main/tools/myst/host/exec_linux.c#L126 SGX target - https://github.com/deislabs/mystikos/blob/main/tools/myst/host/exec.c#L461
> 
> For existing `--perf` functionality you can add - reports time taken to boot and on shutdown reports time spent on each syscall.

Done.

2023-09-24 22:55 UTC, vtikoo approved these changes
PR looks good! @mikbras had a suggestion about "peak_usage" being more clear than "max_usage"(and I agree).

2023-09-25 07:24 UTC, isil-oz commented
> PR looks good! @mikbras had a suggestion about "peak_usage" being more clear than "max_usage"(and I agree).

Updated "max" with "peak".

2023-09-25 17:07 UTC, merged