Raising heap allocation size to accomodate for OpenSSL 3
deislabs/mystikos pull request #1495
Opened 2023-09-13 20:27 UTC by justanotherminh

2023-09-14 18:25 UTC, asvrada approved these changes

2023-09-14 23:20 UTC, CyanDevs requested changes
Could you please add a bit more context to your PR description so we understand why we need to increase the heap size?

Also, please don't include merge commits in your PR: [Merge branch 'deislabs:main' into openssl3](https://github.com/deislabs/mystikos/pull/1495/commits/836d89c07dbaecb6e1ffc3a8e9a42064d5c0db96)

Thanks!

2023-09-15 19:09 UTC, CyanDevs approved these changes
Thanks for the changes!

2023-09-15 20:30 UTC, vtikoo approved these changes
LGTM, thanks for tracking down this issue!

2023-09-15 22:48 UTC, merged