[DO NOT MERGE] Add samples for python Flask and uWSGI
deislabs/mystikos pull request #180
Opened 2021-03-10 11:02 UTC by AevaOnline

Neither sample works right now due to syscall limitations. This is documented within the sample. Uploading to share the test cases.

2021-04-16 15:34 UTC, jxyang commented
Could you retry with #267  merged? @AevaOnline

2021-04-29 17:42 UTC, bodzhang commented
With [#267](https://github.com/deislabs/mystikos/pull/267) merged, Flask sample test now fails due to Python 3 subprocess package [calling fork/exec](https://github.com/python/cpython/blob/76cd81d60310d65d01f9d7b48a8985d8ab89c8b4/Lib/subprocess.py#L1774). 

Python subprocess will [use POSIX_SPAWN on glibc version 2.24 and above ](https://github.com/python/cpython/blob/76cd81d60310d65d01f9d7b48a8985d8ab89c8b4/Lib/subprocess.py#L678). But currently Mytikos implementation doesn't support Ubuntu/glibc Python3 yet.

2021-04-30 12:25 UTC, bodzhang commented
With [#267](https://github.com/deislabs/mystikos/pull/267) merged, Python uWSGI server sample works.  I did need to add "protocol = http" to uwsgi.ini file.

2021-04-30 12:48 UTC, bodzhang commented
Setting Flask to not use multiple process, Flask server also works.  In flask_app.py:

`app.run(debug=True, host='0.0.0.0', port='8000', use_reloader=False)`

2021-04-30 13:06 UTC, bodzhang requested changes

2021-04-30 13:06 UTC, bodzhang commented on solutions/python_web_frameworks/Makefile
> +#run:
Replace with the following:

run:
	test -f server.pid && kill -9 `cat server.pid` || true
	@echo "===start flask server"
	@$(MYST_EXEC) $(OPTS) rootfs /usr/local/bin/python3 /app/flask_app.py & echo $$! > server.pid
	@sleep 10
	curl 127.0.0.1:8000 -w "\n"
	@echo "===stop flask server"
	@test -f server.pid && kill -9 `cat server.pid` && rm server.pid || true
	@echo "===start uwsgi server"
	@$(MYST_EXEC) $(OPTS) rootfs /usr/local/bin/uwsgi /app/uwsgi.ini & echo $$! > server.pid
	@sleep 10
	curl 127.0.0.1:8000 -w "\n"
	@test -f server.pid && kill -9 `cat server.pid` && rm server.pid || true
	@echo "===stop flask server"

server-flask:
	$(MYST_EXEC) $(OPTS) rootfs /usr/local/bin/python3 /app/flask_app.py

server-uwsgi:
	$(MYST_EXEC) $(OPTS) rootfs /usr/local/bin/uwsgi /app/uwsgi.ini

2021-05-26 00:06 UTC, AevaOnline commented
Thanks for the suggestions, @bodzhang ! Incorporated and tested and seems to be passing locally!

2021-05-27 11:45 UTC, bodzhang approved these changes

2021-05-27 12:37 UTC, bodzhang commented
@AevaOnline , just realized that the PR did not add the new solution to /solutions/Makefile. Can you add the needed Makefile change?

2021-06-04 13:35 UTC, bodzhang approved these changes
Can address the needed  change in solutions directory Makefile in a separate PR.

2021-06-04 13:36 UTC, merged