Affinity.rebase
deislabs/mystikos pull request #295
Opened 2021-04-16 16:07 UTC by mikbras

2021-04-21 22:36 UTC, bodzhang requested changes

2021-04-21 22:36 UTC, bodzhang commented on tests/ltp/Makefile
> -
Is the deletion here intentional?

2021-04-21 22:36 UTC, bodzhang commented on include/myst/thread.h
> +    /* the value returned by gettid() on the target (for this thread) */
`myst_gettid()` still returns the internal `tid` above. `myst_sched_getaffinity()` and myst_sched_setaffinity()' perform the internal-tid to `target_tid` translation. The comment should be fixed.

2021-04-22 19:35 UTC, jxyang commented on solutions/aspnet/Makefile
> +OPTS += --memory-size=2048m
This setting should has no effect as the same setting in config.json takes precedence.

2021-04-22 19:35 UTC, jxyang commented on solutions/aspnet/Makefile
> +	sleep 60
60 seconds is probably too much for waiting. Why it takes much longer now to boot Mystikos?

2021-04-22 19:35 UTC, jxyang commented on solutions/python_webserver/Makefile
> +OPTS = --memory-size=1024m
See my comment above.

2021-04-22 19:35 UTC, jxyang commented on include/myst/kernel.h
> +    pid_t target_tid;
This applies to all ethreads. So the comment about just "main thread" is not accurate.

2021-04-22 19:35 UTC, jxyang commented on tools/myst/enc/enc.c
> +#define ENCLAVE_HEAP_SIZE 262144
Is this the OE heap? Why does it need to double?

2021-04-30 20:30 UTC, bodzhang approved these changes

2021-05-01 00:17 UTC, mikbras commented
I found that it takes 5 minutes on a bare metal SGX NUC for the ``aspnet`` solution to run. Previously it took only 1 minute. To work around this, I added the UNIPROCESSOR macro. When defined ``sched_getaffinity`` only reports a single processor, causing ``aspnet`` to run in 60 seconds again.

2021-05-05 14:59 UTC, jxyang commented on include/myst/mman.h
> +int myst_mman_mprotect(myst_mman_t* mman, void* addr, size_t len, int prot);
Do we have to mingle `mprotect` work in this PR?

2021-05-05 14:59 UTC, jxyang commented on samples/openmp/Makefile
> +	OMP_PROC_BIND=true $(MYST_EXEC) $(OPTS) --roothash=roothash ext2rootfs /app/openmp-test
What's this for?

2021-05-12 01:53 UTC, closed without merging