Add tcalls sched_setscheduler, sched_getscheduler
deislabs/mystikos pull request #989
Opened 2021-11-08 03:19 UTC by RRathna

To-do:
1. enable ltp tests. Currently ltp fails with errno 38 - syscall not implemented, same error as before this code change was introduced.
2.  Add SYS_sched_get_priority_max(),
    SYS_sched_get_priority_min(),
     SYS_sched_getparam(),

2021-11-08 18:38 UTC, paulcallen requested changes
There will need tom be some parameter validation on the structure parameters in the kernel, and need to enable the LTP tests for these if possible.

2021-11-11 19:07 UTC, vtikoo commented on kernel/procfs.c
> +    /* Create /proc/sys/kernel directory */
/proc/sys/kernel is not a pid specific entry. `procfs_pid_setup` is called on process creation.

2021-11-11 19:10 UTC, vtikoo commented on kernel/procfs.c
> +    /* Create /proc/sys/kernel directory */
Recommend moving this to `create_proc_root_entries`.

2021-11-11 19:10 UTC, vtikoo commented on kernel/procfs.c
> +        ECHECK(myst_snprintf(
You don't need the string formatting, you could directly use the string literal in `myst_create_virtual_file`.

2021-11-11 19:20 UTC, vtikoo commented on kernel/procfs.c
> +            "/proc/sys/kernel/pid_max"));
This should be a path within /proc mount. So just "/sys/kernel/pid_max".

2022-06-13 22:43 UTC, radhikaj commented
Closing this for now, please reopen if you would like to update

2022-06-13 22:43 UTC, closed without merging